
-- Azure SQL: Sequences
CREATE SEQUENCE SQ_TB_SOULBALANCE_USUARIO AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_TB_SOULBALANCE_ATIVIDADES AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_TB_SOULBALANCE_CHEKIN_MANUAL AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_TB_SOULBALANCE_DADOS_SENSOR AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_TB_SOULBALANCE_RECOMENDACAO AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_TB_SOULBALANCE_ANALISE_IA AS BIGINT START WITH 1 INCREMENT BY 1;


CREATE TABLE TB_SOULBALANCE_USUARIO (
    user_id BIGINT PRIMARY KEY CONSTRAINT DF_TB_SOULBALANCE_USUARIO_ID DEFAULT NEXT VALUE FOR SQ_TB_SOULBALANCE_USUARIO,
    nome NVARCHAR(255) NULL,
    email NVARCHAR(255) NULL,
    senha NVARCHAR(255) NULL,
    data_criacao DATETIME2 NULL
);


CREATE TABLE TB_SOULBALANCE_ATIVIDADE (
    atividade_id BIGINT PRIMARY KEY CONSTRAINT DF_TB_SOULBALANCE_ATIVIDADE_ID DEFAULT NEXT VALUE FOR SQ_TB_SOULBALANCE_ATIVIDADES,
    tipo_atividade NVARCHAR(50) NULL,
    descricao NVARCHAR(255) NULL,
    inicio DATETIME2 NULL,
    fim DATETIME2 NULL,
    duracao_minutos_atividade BIGINT NULL,
    fk_id_usuario BIGINT NULL,
    CONSTRAINT FK_ATIVIDADE_USUARIO FOREIGN KEY (fk_id_usuario) REFERENCES TB_SOULBALANCE_USUARIO(user_id)
);


CREATE TABLE TB_SOULBALANCE_CHEKIN_MANUAL (
    chekin_id BIGINT PRIMARY KEY CONSTRAINT DF_TB_SOULBALANCE_CHEKIN_MANUAL_ID DEFAULT NEXT VALUE FOR SQ_TB_SOULBALANCE_CHEKIN_MANUAL,
    humor NVARCHAR(50) NULL,
    energia NVARCHAR(50) NULL,
    foco NVARCHAR(50) NULL,
    time DATETIME2 NULL,
    fk_id_usuario BIGINT NULL,
    CONSTRAINT FK_CHEKIN_USUARIO FOREIGN KEY (fk_id_usuario) REFERENCES TB_SOULBALANCE_USUARIO(user_id)
);


CREATE TABLE TB_SOULBALANCE_DADOS_SENSOR (
    dado_id BIGINT PRIMARY KEY CONSTRAINT DF_TB_SOULBALANCE_DADOS_SENSOR_ID DEFAULT NEXT VALUE FOR SQ_TB_SOULBALANCE_DADOS_SENSOR,
    tipo_dado NVARCHAR(50) NULL,
    valor INT NULL,
    time DATETIME2 NULL,
    fk_id_usuario BIGINT NULL,
    CONSTRAINT FK_DADOS_USUARIO FOREIGN KEY (fk_id_usuario) REFERENCES TB_SOULBALANCE_USUARIO(user_id)
);


CREATE TABLE TB_EMAIL (
    emailId UNIQUEIDENTIFIER PRIMARY KEY CONSTRAINT DF_TB_EMAIL_ID DEFAULT NEWID(),
    owner_ref NVARCHAR(255) NULL,
    email_from NVARCHAR(255) NULL,
    email_to NVARCHAR(255) NULL,
    subject NVARCHAR(255) NULL,
    text NVARCHAR(MAX) NULL,
    send_date_email DATETIME2 NULL,
    status_email NVARCHAR(50) NULL
);


CREATE TABLE TB_SOULBALANCE_RECOMENDACAO (
    recomendacao_id BIGINT PRIMARY KEY CONSTRAINT DF_TB_SOULBALANCE_RECOMENDACAO_ID DEFAULT NEXT VALUE FOR SQ_TB_SOULBALANCE_RECOMENDACAO,
    sugestao NVARCHAR(255) NULL,
    time DATETIME2 NULL,
    fk_id_usuario BIGINT NULL,
    CONSTRAINT FK_RECOMENDACAO_USUARIO FOREIGN KEY (fk_id_usuario) REFERENCES TB_SOULBALANCE_USUARIO(user_id)
);


CREATE TABLE TB_SOULBALANCE_ANALISE_IA (
    analise_id BIGINT PRIMARY KEY CONSTRAINT DF_TB_SOULBALANCE_ANALISE_IA_ID DEFAULT NEXT VALUE FOR SQ_TB_SOULBALANCE_ANALISE_IA,
    data_referencia DATE NOT NULL UNIQUE,
    resumo_narrativo_ia NVARCHAR(MAX) NULL,
    alerta_urgente BIT NULL,
    fadiga_score_calculado FLOAT NULL,
    estresse_score_calculado FLOAT NULL,
    data_criacao DATETIME2 NULL,
    fk_id_usuario BIGINT NOT NULL,
    CONSTRAINT FK_ANALISEIA_USUARIO FOREIGN KEY (fk_id_usuario) REFERENCES TB_SOULBALANCE_USUARIO(user_id)
);